Repository beyond-sw-camp/be08-fin-3Dasoo-SalesBoost-FE, pull requests merged in 2024-10, with the labels that each got.

#12 [Feat/#4] 캘린더 레이아웃 및 할 일 생성
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/assets/logo.svg
  src/components/HelloWorld.vue
  src/main.js
  src/plugins/vuetify.js
  src/plugins/webfontloader.js
  src/router/router.js
  src/views/calendar/CalendarView.vue
  vite.config.js
Labels: front, feat, style

#15 [Feat/#14] 영업 활동 등록 페이지 및 기능 구현
  src/router/router.js
  src/views/act/ActView.vue
  src/views/calendar/CalendarView.vue
  src/views/calendar/calendar.css
Labels: front, feat, style

#22 [Feat/#19] Plan 주간 및 일간 달력 기능 구현
  src/components/modal/PlanModal.vue
  src/views/apps/calendar/FullCalender.vue
Labels: bug, front, feat

#26 [Feat/#25] 로그인 & 회원가입 구현
  .npmrc
  src/components/auth/LoginForm.vue
  src/components/auth/SignUpForm.vue
  src/router/AuthRoutes.ts
  src/stores/auth.ts
  src/views/authentication/Login.vue
  src/views/authentication/SignUp.vue
Labels: design, front, feat, style

#28 [Feat/#20] 캘린더 plan, todo 세부 일정 조회
  src/components/modal/PlanModal.vue
  src/components/modal/TodoModal.vue
  src/views/apps/calendar/FullCalender.vue
  src/views/apps/calendar/calendar.css
Labels: front, feat

#31 feat: #21 Proposal 제안 조회 페이지 및 기능 구현 (등록, 삭제)
  src/components/proposal/ProposalList.vue
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
Labels: front, feat

#33 [Feat/#30] 메인 페이지 구현
  src/components/sales/main/Act.vue
  src/components/sales/main/Lead.vue
  src/components/sales/main/MonthSale.vue
  src/components/sales/main/Notice.vue
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
  src/views/sales/Contact.vue
  src/views/sales/Main.vue
  src/views/sales/Notice.vue
Labels: design, front, feat

#35 [Feat/#34] Todo 유효성 추가 및 Alert창 개선
  src/components/modal/PlanModal.vue
  src/components/modal/TodoModal.vue
  src/views/apps/calendar/FullCalender.vue
Labels: design, front, feat, style

#36 feat : #11 계약 페이지 기능 연결 완료
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
  src/views/apps/contract/ContractDetailView.vue
  src/views/apps/contract/ContractModal.vue
  src/views/apps/contract/ContractView.vue
Labels: front, feat

#38 [Fix/#24] actForm 유효성 검증 구현
  src/views/apps/calendar/act/ActView.vue
Labels: bug, front, feat, style

#39 [Feat/#27] 고객 목록 조회 API 연결
  src/_mockApis/components/widget/card.ts
  src/components/auth/LoginForm.vue
  src/components/auth/SignUpForm.vue
  src/components/customer/CustomerAddCard.vue
  src/components/customer/CustomerCard.vue
  src/components/customer/FilterCard.vue
  src/components/customer/InputForm.vue
  src/router/MainRoutes.ts
  src/views/apps/customer/Customer.vue
  src/views/apps/customer/CustomerAdd.vue
  src/views/apps/customer/CustomerDetail.vue
  src/views/authentication/Login.vue
Labels: front, feat

#40 feat : #31 sales 기본 페이지 구현 카드 형식으로 구현
  src/router/MainRoutes.ts
  src/views/apps/contract/ContractDetailView.vue
  src/views/apps/sales/SalesDetailView.vue
  src/views/apps/sales/SalesModal.vue
  src/views/apps/sales/SalesView.vue
Labels: front, feat

#43 [Feat/#29] 캘린더 필터 기능 구현
  src/components/modal/PlanModal.vue
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
  src/stores/apps/calendar/calendar.js
  src/views/apps/calendar-template/Calendar.vue
  src/views/apps/calendar-template/Events.ts
  src/views/apps/calendar-template/FullCalender.vue
  src/views/apps/calendar/Calendar.vue
  src/views/apps/calendar/CalendarFilters.vue
  src/views/apps/calendar/FullCalender.vue
  src/views/apps/calendar/calendar.css
Labels: design, front, refact, feat, style

#48 [Feat/#45] contract, sales 코드 수정
  src/views/apps/contract/ContractDetailView.vue
  src/views/apps/sales/SalesDetailView.vue
  src/views/apps/sales/SalesModal.vue
Labels: front, refact, style

#51 [Feat/#32] estimate 제안 메인 조회 페이지 및 등록/삭제 기능구현
  src/components/estimate/CreateEstimate.vue
  src/components/estimate/EstimateList.vue
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
Labels: front, feat

#50 [Feat/#49] addChart 사이드바 차트탭 생성
  src/layouts/full/vertical-sidebar/sidebarItem.ts
Labels: front, feat

#54 [Style/#53] 로고 및 에러 페이지 이미지 추가
  src/assets/images/backgrounds/error2.svg
  src/assets/images/logos/logolight.svg
  src/views/authentication/Error.vue
Labels: design, front

#56 [Feat/#55] 부서 관련 페이지 추가
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
  src/views/apps/department/Department.vue
Labels: design, feat

#59 [Feat/#47] axios 관련 작업
  src/api/axiosinterceptor.js
  src/api/baseapi.js
  src/components/auth/LoginForm.vue
  src/components/auth/SignUpForm.vue
  src/components/customer/InputForm.vue
  src/components/customer/UpdateForm.vue
  src/router/index.ts
  src/stores/auth.ts
  src/views/apps/customer/Customer.vue
Labels: front, refact, feat

#63 [Fix] 새로고침시 로그인 풀림 해결
  src/components/auth/LoginForm.vue
  src/router/index.ts
  src/stores/auth.ts
Labels: front, refact

#62 [refact/#52] proposal 제안 사이드바 메뉴 위치이동 및 axios에서 api로 수정
  src/components/proposal/ProposalList.vue
  src/layouts/full/vertical-sidebar/sidebarItem.ts
Labels: front, refact

#69 [Fix/#61] 인증번호 체크 관련 에러 수정
  src/components/auth/SignUpForm.vue
Labels: bug, front, feat

#70 [Feat/#67] proposal 제안 수정기능 구현 및 영업기회 데이터 연결
  src/components/proposal/CreateProposal.vue
  src/components/proposal/ProposalList.vue
Labels: front, feat

#71 [Feat/#44] 영업활동 리스트 구현
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
  src/utils/ActStatusMappings.js
  src/views/apps/calendar/FullCalender.vue
  src/views/apps/calendar/act/ActList.vue
  src/views/apps/calendar/act/ActView.vue
  src/views/apps/calendar/act/FormCustom.vue
Labels: bug, front, feat, style

#73 [Feat/#46] Todo 삭제 기능 구현
  src/components/modal/ConfirmDialogs.vue
  src/components/modal/TodoModal.vue
  src/views/apps/calendar/FullCalender.vue
Labels: front, feat

#77 [Feat/#76] 영업기회 관련 페이지 개발
  package-lock.json
  package.json
  src/components/lead/DetailForm.vue
  src/components/sales/main/Lead.vue
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
  src/views/apps/lead/Lead.vue
  src/views/apps/lead/LeadDetail.vue
  src/views/apps/lead/LeadNew.vue
Labels: design, front, feat

#79 [Feat/#64] 잠재고객 관련 페이지 디자인 및 API 연결
  src/components/customer/InputForm.vue
  src/components/pcustomer/pCustomerAddCard.vue
  src/components/pcustomer/pCustomerCard.vue
  src/components/pcustomer/pCustomerHistoryCard.vue
  src/components/pcustomer/pCustomerInputForm.vue
  src/components/pcustomer/pCustomerUpdateForm.vue
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
  src/views/apps/pCustomer/pCustomer.vue
  src/views/apps/pCustomer/pCustomerAdd.vue
  src/views/apps/pCustomer/pCustomerDetail.vue
Labels: design, front, feat, style

#81 [Feat/#80] 영업 활동 차트 구현
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
  src/utils/ActStatusMappings.js
  src/views/apps/sbChart/ActChart.vue
  src/views/apps/sbChart/ActChartClsCount.vue
  src/views/apps/sbChart/ActChartCount.vue
  src/views/apps/sbChart/ActChatUserRatio.vue
  tsconfig.json
Labels: chore, front, feat

#83 [Feat/#64] 접촉 이력 관련 화면 디자인 & API 연결
  src/components/pcustomer/ConfirmDialogs.vue
  src/components/pcustomer/HistoryModal.vue
  src/components/pcustomer/pCustomerUpdateForm.vue
  src/views/apps/pCustomer/pCustomerAdd.vue
  src/views/apps/pCustomer/pCustomerDetail.vue
Labels: design, front, feat

#85 [Feat/#84] 목표 매출 관리 페이지 구현
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
  src/views/apps/targetSale/TargetSale.vue
Labels: design

#86 [Feat/#78] Act에 Lead 연결
  src/utils/ActStatusMappings.js
  src/views/apps/calendar/act/Act.css
  src/views/apps/calendar/act/ActView.vue
Labels: front, feat, style

#89 [Feat/#87] Plan 분류에 도메인 연결 기능 추가
  src/components/modal/PlanModal.vue
  src/utils/PlanMappings.js
  src/views/apps/calendar/FullCalender.vue
Labels: bug, front, refact, feat

#92 [Feat/#90] Plan 및 Act 수정, 삭제
  src/components/modal/PlanModal.vue
  src/components/modal/TodoModal.vue
  src/utils/PlanMappings.js
  src/views/apps/calendar/FullCalender.vue
  src/views/apps/calendar/act/ActList.vue
  src/views/apps/calendar/act/ActView.vue
Labels: front, refact, feat

#95 [Target sale/#84] 프로세스 생성/ 조회/ 삭제 api 연결 목표 매출 조회 api 연결
  src/views/apps/department/Department.vue
  src/views/apps/process/Process.vue
  src/views/apps/targetSale/TargetSale.vue
Labels: feat

#96 [Feat/#88] 고객 관련 프론트 개발 완성
  src/components/customer/CustomerCard.vue
  src/components/customer/FilterCard.vue
  src/components/customer/InputForm.vue
  src/components/customer/UpdateForm.vue
  src/components/pcustomer/pCustomerCard.vue
  src/views/apps/customer/Customer.vue
  src/views/apps/pCustomer/pCustomerDetail.vue
Labels: design, front, refact, feat, style

#98 [Product/#97] 제품 관련 조회/삭제/생성 api 연결
  src/views/apps/product/Product.vue
Labels: feat

#100 [Feat/#99] 부서 api 연결
  src/views/apps/department/Department.vue
Labels: front, feat

#102 [Feat/#93] 메인페이지 고객, 잠재고객, 영업기회, 영업활동 통계 api 연동
  src/components/lead/DetailForm.vue
  src/components/sales/main/Act.vue
  src/components/sales/main/Customer.vue
  src/components/sales/main/Lead.vue
  src/components/sales/main/LeadAct.vue
  src/components/sales/main/MonthSale.vue
  src/components/sales/main/Notice.vue
  src/components/sales/main/Sales.vue
  src/views/apps/lead/Lead.vue
  src/views/sales/Main.vue
Labels: design, front, feat, style

#103 [Feat/#41] 로그인한 사용자의 캘린더 관리
  src/views/apps/calendar/FullCalender.vue
Labels: front, feat

#105 [Feat/#101] 잠재고객 관련기능 완성
  src/components/pcustomer/HistoryModal.vue
  src/components/pcustomer/pCustomerInputForm.vue
  src/components/pcustomer/pCustomerUpdateForm.vue
  src/components/pcustomer/pFilterCard.vue
  src/views/apps/pCustomer/pCustomer.vue
  src/views/apps/pCustomer/pCustomerDetail.vue
Labels: design, front, feat

#106 [Feat/#84] 목표 매출 디자인 수정 및 api 연결
  src/views/apps/process/Process.vue
  src/views/apps/targetSale/TargetSale.vue
Labels: design, front, feat

#110 [Feat/#84] 목표 매출 디자인 수정
  src/views/apps/targetSale/TargetSale.vue
Labels: design, front

#111 [Feat/#49] 차트 생성 및 api 적용
  package-lock.json
  package.json
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/MainRoutes.ts
  src/views/apps/contract/ContractDetailView.vue
  src/views/apps/sales/SalesChartView.vue
  src/views/apps/sales/SalesDetailView.vue
  src/views/apps/sales/SalesModal.vue
  src/views/apps/sales/SalesPredictionChartView.vue
  src/views/apps/sales/SalesStatusChartView.vue
Labels: design, front, refact, feat, style

#113 [Feat/#112] 부서 페이지 입력 폼 수정
  src/views/apps/department/Department.vue
Labels: design, refact

#116 [Feat/115] 프로세스 페이지 url 변경 및 입력창 수정
  src/views/apps/department/Department.vue
  src/views/apps/process/Process.vue
  src/views/apps/product/Product.vue
  src/views/apps/targetSale/TargetSale.vue
Labels: front, refact, feat

#117 [Design/#114] Horizontal 사이드바로 변경
  src/layouts/full/FullLayout.vue
  src/layouts/full/horizontal-header/HorizontalHeader.vue
  src/layouts/full/horizontal-sidebar/HorizontalSidebar.vue
  src/layouts/full/horizontal-sidebar/horizontalItems.ts
  src/layouts/full/vertical-header-backup/LanguageDD.vue
  src/layouts/full/vertical-header-backup/NotificationDD.vue
  src/layouts/full/vertical-header-backup/ProfileDD.vue
  src/layouts/full/vertical-header-backup/Searchbar.vue
  src/layouts/full/vertical-header-backup/ThemeToggler.vue
  src/layouts/full/vertical-header-backup/VerticalHeader.vue
Labels: front, refact, style

#123 [Feat/121] 수정/검색 api 연결 및 디자인 수정
  src/views/apps/product/Product.vue
Labels: front, refact, feat

#122 [Refact/#120] 잠재고객 요구사항 변경 및 코드 정리
  src/components/customer/FilterCard.vue
  src/components/pcustomer/pCustomerInputForm.vue
  src/views/apps/customer/Customer.vue
  src/views/apps/pCustomer/pCustomer.vue
Labels: design, chore, front, refact, style

#124 [Feat/#115] 프로세스 수정 api 연결 및 기본 프로세스 설정 디자인 변경
  src/views/apps/process/Process.vue
Labels: design, front, refact, feat

#125 [Fix/#120] 캘린더 페이지 접속 에러 수정
  src/api/axiosinterceptor.js
  src/views/apps/calendar/FullCalender.vue
Labels: bug, front

#128 [Refact/#127] 메인 페이지 퍼센트 포맷팅 수정, 리드 상세 고객 팝업 통해 고객 선택
  src/components/lead/DetailForm.vue
  src/views/sales/Main.vue
Labels: front, refact, feat

#130 [Feat/#129] 부서 수정 api 연결 및 디자인 수정
  src/views/apps/department/Department.vue
  src/views/apps/product/Product.vue
Labels: design, front, feat

#131 [Feat/#91]견적 등록 시 제품 등록 기능 구현 및 기본 기능 수정
  src/components/estimate/CreateEstimate.vue
  src/components/estimate/DetailEstimate.vue
  src/components/estimate/ListEstimate.vue
  src/router/MainRoutes.ts
Labels: feat

#135 [Design/#134] FullLayout 적용
  index.html
  src/components/estimate/ListEstimate.vue
  src/components/proposal/ProposalList.vue
  src/layouts/full/FullLayout.vue
  src/layouts/full/horizontal-header/HorizontalHeader-backup.vue
  src/layouts/full/vertical-header-backup/LanguageDD.vue
  src/layouts/full/vertical-header-backup/NotificationDD.vue
  src/layouts/full/vertical-header-backup/ProfileDD.vue
  src/layouts/full/vertical-header-backup/Searchbar.vue
  src/layouts/full/vertical-header-backup/ThemeToggler.vue
  src/layouts/full/vertical-header-backup/VerticalHeader.vue
  src/layouts/horizontal-sidebar-backup/HorizontalSidebar.vue
  src/layouts/horizontal-sidebar-backup/NavCollapse/Index.vue
  src/layouts/horizontal-sidebar-backup/NavItem/Index.vue
  src/layouts/horizontal-sidebar-backup/horizontalItems.ts
  src/scss/_variables.scss
  src/scss/components/_VCard.scss
  src/scss/layout/_container.scss
  src/views/apps/calendar/Calendar.vue
  src/views/apps/customer/Customer.vue
  src/views/apps/department/Department.vue
  src/views/apps/lead/Lead.vue
  src/views/apps/pCustomer/pCustomer.vue
  src/views/apps/sales/SalesDetailView.vue
  src/views/sales/Main.vue
Labels: design, front, refact

#137 [Refact/136] 공통 컴포넌트 및 레이아웃 통일 작업
  src/components/customer/InputForm.vue
  src/components/customer/UpdateForm.vue
  src/components/estimate/CreateEstimate.vue
  src/components/estimate/DetailEstimate.vue
  src/components/estimate/EstimateList.vue
  src/components/estimate/ListEstimate.vue
  src/components/lead/DetailForm.vue
  src/components/modal/PlanModal.vue
  src/components/modal/TodoModal.vue
  src/components/proposal/CreateProposal.vue
  src/components/proposal/ProposalList.vue
  src/components/shared/AlertComponent.vue
  src/components/shared/ConfirmDialogs.vue
  src/components/shared/EditConfirmDialog.vue
  src/layouts/full/horizontal-sidebar/horizontalItems.ts
  src/scss/components/_VCard.scss
  src/utils/useAlert.js
  src/views/apps/calendar/Calendar.vue
  src/views/apps/calendar/FullCalender.vue
  src/views/apps/calendar/act/Act.css
  src/views/apps/calendar/act/ActList.vue
  src/views/apps/calendar/act/ActView.vue
  src/views/apps/contract/ContractDetailView.vue
  src/views/apps/contract/ContractModal.vue
  src/views/apps/contract/ContractView.vue
  src/views/apps/customer/Customer.vue
  src/views/apps/department/Department.vue
  src/views/apps/lead/Lead.vue
  src/views/apps/pCustomer/pCustomer.vue
  src/views/apps/process/Process.vue
  src/views/apps/product/Product.vue
  src/views/apps/sales/SalesChartView.vue
  src/views/apps/sales/SalesDetailView.vue
  src/views/apps/sales/SalesModal.vue
  src/views/apps/sales/SalesPredictionChartView.vue
  src/views/apps/sales/SalesStatusChartView.vue
  src/views/apps/sbChart/ActChart.vue
  src/views/apps/sbChart/ActChartCount.vue
  src/views/apps/targetSale/TargetSale.vue
Labels: design, front, refact, style

#139 [Feat/#138] 관리자 메뉴 및 권한 기능 개선
  src/_mockApis/headerData.ts
  src/components/apps/user/MyIntroCard.vue
  src/components/auth/LoginForm.vue
  src/layouts/full/horizontal-sidebar/HorizontalSidebar.vue
  src/layouts/full/horizontal-sidebar/horizontalItems.ts
  src/layouts/full/vertical-header/ProfileDD.vue
  src/router/MainRoutes.ts
  src/router/index.ts
  src/stores/auth.ts
Labels: design, chore, front, feat

#141 [Feat/#140] 고객 삭제, 수정 로직 변경
  src/components/customer/UpdateForm.vue
Labels: design, front, feat

#142 [Feat/#127] 영업기회 파이프라인 컴포넌트 추가
  src/components/lead/DetailForm.vue
  src/components/lead/Timeline.vue
  src/views/apps/lead/LeadDetail.vue
  src/views/sales/Main.vue
Labels: bug, front, feat

#144 style: #143 Estimate 견적 견적 디자인 수정 - 제목 및 상단 결과
  src/components/estimate/ListEstimate.vue
Labels: design, front

#147 [Feat/#118] 일정 목록 페이지
  src/components/apps/plan/PlanEditable.vue
  src/components/modal/PlanModal.vue
  src/router/MainRoutes.ts
  src/utils/PlanMappings.js
  src/views/apps/plan/PlanList.vue
Labels: front, feat

#148 [Style/#145] Proposal 제안 제목 및 상단 결과 디자인 수정
  src/components/proposal/CreateProposal.vue
  src/components/proposal/ProposalList.vue
Labels: design, front

#149 [Feat/#146] 잠재고객 삭제, 수정 로직 변경
  src/components/pcustomer/pCustomerUpdateForm.vue
Labels: design, front, feat

#151 [Design/#150] 제품 페이지 공통 속성 적용 및 수정
  src/router/MainRoutes.ts
  src/views/apps/product/Product.vue
Labels: design, front, feat

#160 [Feat/#159] 이메일 인증완료 시 버튼 비활성화
  src/components/auth/SignUpForm.vue
Labels: feat

#155 [Design/#154] 프로세스 공통 속성 적용 및 수정
  src/views/apps/department/Department.vue
  src/views/apps/process/Process.vue
Labels: design, front, refact, feat

#164 [Refact/#163] Proposal 제안 영업기회 선택 테이블 형식으로 변경 및 검색 추가
  src/components/proposal/CreateProposal.vue
Labels: design, front, refact

#165 [Feat/#161] 비밀번호 변경 기능 화면 구현 및 API 연결
  src/api/axiosinterceptor.js
  src/components/auth/LoginForm.vue
  src/components/auth/ResetForm.vue
  src/components/auth/SignUpForm.vue
  src/components/modal/PasswordResetModal.vue
  src/router/AuthRoutes.ts
  src/router/MainRoutes.ts
  src/views/authentication/BoxedForgotPassword.vue
  src/views/authentication/ChangePassword.vue
  src/views/authentication/FindPassword.vue
  src/views/authentication/SideRegister.vue
Labels: front, feat

#166 [Refact/#127] 메인 부서 검색 추가 및 공통 사항 적용
  src/components/lead/DetailForm.vue
  src/components/lead/Timeline.vue
  src/components/sales/main/LeadAct.vue
  src/components/sales/main/Sales.vue
  src/views/apps/calendar/act/ActList.vue
  src/views/apps/lead/Lead.vue
  src/views/sales/Main.vue
Labels: bug, front, refact, style

#167 [Design/#152] 목표 매출 페이지(& 제품 페이지) 공통 사항 적용
  src/views/apps/product/Product.vue
  src/views/apps/targetSale/TargetSale.vue
Labels: design, front, feat

#168 [Design/#154] 하위 프로세스 삭제시에도 프로세스 재로딩
  src/views/apps/process/Process.vue
Labels: bug, front

#172 [Feat/#118] Todo List 구현
  src/components/modal/TodoModal.vue
  src/components/shared/AlertComponent.vue
  src/layouts/full/horizontal-header/HorizontalHeader.vue
  src/layouts/full/horizontal-sidebar/horizontalItems.ts
  src/router/MainRoutes.ts
  src/scss/layout/_container.scss
  src/utils/PlanMappings.js
  src/views/apps/calendar/CalendarFilters.vue
  src/views/apps/calendar/FullCalender.vue
  src/views/apps/calendar/act/Act.css
  src/views/apps/calendar/act/ActList.vue
  src/views/apps/calendar/act/ActView.vue
  src/views/apps/calendar/calendar.css
  src/views/apps/todo/TodoList.vue
  src/views/apps/todo/todolist.css
Labels: front, feat, style

#174 [Design/#173] 목표 매출 테이블 액션 삭제
  src/views/apps/targetSale/TargetSale.vue
Labels: design, front
