Repository beyond-sw-camp/be08-fin-3Dasoo-SalesBoost-FE, pull requests merged in 2024-11, with the labels that each got.

#178 [Feat#176] 계약 관련 차트 구현
  src/layouts/full/horizontal-sidebar/horizontalItems.ts
  src/router/MainRoutes.ts
  src/views/apps/statusChart/ContractChartAmt.vue
  src/views/apps/statusChart/ContractChartClsCount.vue
  src/views/apps/statusChart/contractChart.vue
Labels: front, feat

#179 Front ci/cd
  .github/workflows/deploy.yml
Labels: front, deploy

#182 [Fix/#180] todoList js 파일 누락 수정
  src/stores/apps/todo/tasktodo.js
  src/views/apps/todo/TodoList.vue
Labels: bug, front

#185 [Feat/#184] 견적 및 제안 검색조건 기능 추가
  package-lock.json
  package.json
  src/components/estimate/ListEstimate.vue
  src/components/proposal/ProposalList.vue
  src/layouts/full/horizontal-sidebar/horizontalItems.ts
  src/router/MainRoutes.ts
  src/views/apps/contract/ContractDetailView.vue
  src/views/apps/contract/ContractEdit.vue
  src/views/apps/contract/ContractFilterView.vue
  src/views/apps/contract/ContractModal.vue
  src/views/apps/contract/ContractView.vue
  src/views/apps/sales/SalesChartView.vue
  src/views/apps/sales/SalesCreate.vue
  src/views/apps/sales/SalesDetailView.vue
  src/views/apps/sales/SalesEdit.vue
  src/views/apps/sales/SalesFilterView.vue
  src/views/apps/sales/SalesModal.vue
  src/views/apps/sales/SalesPredictionChartView.vue
  src/views/apps/sales/SalesStatusChartView.vue
  src/views/apps/sales/SalesView.vue
  tsconfig.json
Labels: front, feat

#186 [Chore] API 배포 url 주소 변경
  src/api/axiosinterceptor.js
  src/api/baseapi.js
Labels: front, deploy

#189 [Feat/#188] 목표 매출 수정시에도 단위당 콤마 나오도록 수정
  src/views/apps/targetSale/TargetSale.vue
Labels: front, feat

#192 [Feat/#127] 영업 예측 페이지 구현
  src/components/auth/LoginForm.vue
  src/components/lead/DetailForm.vue
  src/components/lead/Month.vue
  src/components/lead/Path.vue
  src/components/lead/Process.vue
  src/components/lead/Status.vue
  src/components/lead/Success.vue
  src/components/sales/main/Customer.vue
  src/layouts/full/horizontal-sidebar/horizontalItems.ts
  src/router/MainRoutes.ts
  src/stores/auth.ts
  src/views/apps/lead/Lead.vue
  src/views/apps/lead/LeadChart.vue
  src/views/sales/Main.vue
Labels: design, front, refact, feat

#195 [Feat/#193] 전사일정 구현 및 캘린더 에러 수정
  src/components/modal/PlanModal.vue
  src/components/modal/TodoModal.vue
  src/stores/apps/calendar/calendarStore.js
  src/utils/PlanMappings.js
  src/views/apps/calendar/CalendarFilters.vue
  src/views/apps/calendar/FullCalender.vue
  src/views/apps/calendar/calendar.css
Labels: bug, front, feat

#200 [Feat/#199] 목표 매출 차트 페이지 필터 구현
  src/views/apps/targetSale/TargetSaleChartView.vue
Labels: front, feat

#202 [Refact/#194] 회원/로그인/회원가입 기능 보완
  src/api/axiosinterceptor.js
  src/api/baseapi.js
  src/components/apps/user/MyProfileBanner.vue
  src/components/auth/LoginForm.vue
  src/components/auth/SignUpForm.vue
  src/components/customer/CustomerCard.vue
  src/layouts/full/vertical-header/ProfileDD.vue
  src/stores/auth.ts
  src/stores/userInfo.js
  src/views/apps/user/MyCustomers.vue
  src/views/apps/user/MyPCustomers.vue
Labels: design, front, feat

#204 [Feat/#203] 실적/매출 차트 페이지 구현
  src/layouts/full/horizontal-sidebar/horizontalItems.ts
  src/router/MainRoutes.ts
  src/views/apps/sales/PerformanceAndSalesChartView.vue
Labels: design, front, feat

#201 [Feat/#197] 영업활동 내 영업기회 가져오기 모달 수정
  src/components/modal/PlanModal.vue
  src/components/modal/TodoModal.vue
  src/views/apps/calendar/FullCalender.vue
  src/views/apps/calendar/act/Act.css
  src/views/apps/calendar/act/ActView.vue
  src/views/apps/calendar/calendar.css
Labels: bug, front, feat

#210 [Design/#209] 프로세스 페이지 하위 프로세스 진행 단계 입력 드롭다운으로 변경
  src/views/apps/process/Process.vue
Labels: design, front

#213 [Feat/#198] 견적 관련 페이지 구현
  src/api/axiosinterceptor.js
  src/api/baseapi.js
  src/components/estimate/CreateEstimate.vue
  src/components/estimate/DetailEstimate.vue
  src/components/estimate/EstimateList.vue
  src/components/lead/DetailForm.vue
  src/composables/useExcel.js
  src/layouts/full/horizontal-sidebar/horizontalItems.ts
  src/router/MainRoutes.ts
  src/views/apps/estimate/EstimateDetail.vue
  src/views/apps/estimate/EstimateList.vue
  src/views/apps/lead/Lead.vue
  src/views/apps/lead/LeadDetail.vue
Labels: front, refact, feat

#214 [User/#207] 프로필 사진 업로드
  src/components/apps/user/MyIntroCard.vue
  src/components/apps/user/MyProfileBanner.vue
  src/layouts/full/vertical-header/ProfileDD.vue
  src/views/apps/user/MyPage.vue
Labels: front, feat

#215 [Refact/#208] Proposal 제안 등록 시 영업기회 검색 및 수정 페이지 레이아웃 변경
  src/components/proposal/CreateProposal.vue
  src/components/proposal/ProposalList.vue
  src/router/MainRoutes.ts
Labels: front, refact

#216 [Refact:/#208] Proposal 제안 detail 파일 추가
  src/components/proposal/DetailProposal.vue
Labels: front, refact

#220 refact: #219 필수 항목 유효성 추가
  src/components/proposal/CreateProposal.vue
Labels: front, refact

#221 [Feat/#190] 매출 및 계약 수정
  src/router/MainRoutes.ts
  src/views/apps/contract/ContractDetailView.vue
  src/views/apps/contract/ContractEdit.vue
  src/views/apps/contract/ContractView.vue
  src/views/apps/sales/SalesDetailView.vue
  src/views/apps/sales/SalesEdit.vue
Labels: design, front, feat

#224 [Refact/#223] plan computed 구조 수정
  src/components/modal/PlanModal.vue
  src/views/apps/estimate/EstimateList.vue
Labels: front, refact

#227 [Feat/#222] 제안 권한 필터 추가
  src/components/proposal/ProposalList.vue
  src/views/apps/estimate/EstimateList.vue
  src/views/apps/lead/Lead.vue
  src/views/sales/Main.vue
Labels: front, feat

#229 [Fix/#228] 리스트에서 사용자의 데이터만 조회
  src/components/apps/plan/PlanEditable.vue
  src/components/auth/LoginForm.vue
  src/stores/apps/calendar/calendarFilterStore.js
  src/stores/apps/calendar/calendarStore.js
  src/stores/apps/todo/tasktodo.js
  src/views/apps/calendar/CalendarFilters.vue
  src/views/apps/calendar/FullCalender.vue
  src/views/apps/calendar/act/ActList.vue
  src/views/apps/todo/TodoList.vue
Labels: bug, front, feat

#233 [Refact/#190] 차트 수정
  src/views/apps/sales/SalesPredictionChartView.vue
  src/views/apps/sales/SalesStatusChartView.vue
Labels: front, refact

#230 Feat: #176 계약현황 차트에 작은 대시보드 카드 추가
  src/router/MainRoutes.ts
  src/views/apps/statusChart/ContractCardAmt.vue
  src/views/apps/statusChart/ContractCardCount.vue
  src/views/apps/statusChart/ContractChartClsCount.vue
  src/views/apps/statusChart/contractChart.vue
Labels: front, feat

#232 [Feat/#231] 상위 프로세스 삭제 수정
  src/views/apps/process/Process.vue
Labels: bug, front

#236 [Design/#235] 제안, 견적명 클릭시 상세보기 이동
  src/components/proposal/CreateProposal.vue
  src/components/proposal/DetailProposal.vue
  src/components/proposal/ProposalList.vue
  src/views/apps/estimate/EstimateDetail.vue
  src/views/apps/estimate/EstimateList.vue
Labels: design, front

#237 [Fix/#234] 전사일정 필터 제거
  src/views/apps/calendar/CalendarFilters.vue
  src/views/apps/calendar/FullCalender.vue
Labels: bug, front, feat

#239 [Feat/#238] 목표 매출 차트 및 실적 매출 차트 관리자만 보이도록 수정 및 부서 삭제시 메시지 출력
  src/layouts/full/horizontal-sidebar/HorizontalSidebar.vue
  src/layouts/full/horizontal-sidebar/horizontalItems.ts
  src/layouts/full/vertical-sidebar/sidebarItem.ts
  src/router/index.ts
  src/views/apps/department/Department.vue
Labels: front, feat

#240 [Refact/#222] 고객, 영업기회, 제안 팝업 권한 설정 추가
  src/components/lead/DetailForm.vue
  src/components/proposal/CreateProposal.vue
  src/components/proposal/DetailProposal.vue
  src/components/proposal/ProposalList.vue
  src/composables/useExcel.js
  src/views/apps/estimate/EstimateDetail.vue
  src/views/apps/estimate/EstimateList.vue
  src/views/apps/lead/Lead.vue
  src/views/sales/Main.vue
Labels: front, refact, feat

#241 [Refact/#190] 단위 붙이기, 필터 크기 조절
  src/views/apps/contract/ContractEdit.vue
  src/views/apps/contract/ContractView.vue
  src/views/apps/sales/SalesEdit.vue
  src/views/apps/sales/SalesView.vue
Labels: front, refact

#245 [Feat/#244] 실적 매출 api 수정 및 색상 변경
  src/views/apps/sales/PerformanceAndSalesChartView.vue
Labels: front, feat

#248 [Design/#247] 부서 등록시 '' 출력 제거
  src/views/apps/department/Department.vue
Labels: design, front

#250 [Feat/#249] 견적 사이드 바 주소 변경
  src/layouts/full/vertical-sidebar/sidebarItem.ts
Labels: front, feat

#252 [Feat/#251] 부서 수정모드 아닐시 상위부서 입력 안되도록 수정
  src/views/apps/department/Department.vue
Labels: front, feat
